# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: torcs_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='torcs_data.proto',
  package='',
  serialized_pb=_b('\n\x10torcs_data.proto\"\x8b\x01\n\tTorcsData\x12\r\n\x05width\x18\x01 \x03(\x05\x12\x0e\n\x06height\x18\x02 \x03(\x05\x12\r\n\x05image\x18\x03 \x03(\x0c\x12\x11\n\tsave_flag\x18\x04 \x03(\x05\x12\x13\n\x0bsteer_angle\x18\x05 \x03(\x01\x12\x0b\n\x03red\x18\x06 \x03(\x0c\x12\r\n\x05green\x18\x07 \x03(\x0c\x12\x0c\n\x04\x62lue\x18\x08 \x03(\x0c')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TORCSDATA = _descriptor.Descriptor(
  name='TorcsData',
  full_name='TorcsData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='TorcsData.width', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='height', full_name='TorcsData.height', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image', full_name='TorcsData.image', index=2,
      number=3, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='save_flag', full_name='TorcsData.save_flag', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='steer_angle', full_name='TorcsData.steer_angle', index=4,
      number=5, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='red', full_name='TorcsData.red', index=5,
      number=6, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='green', full_name='TorcsData.green', index=6,
      number=7, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='blue', full_name='TorcsData.blue', index=7,
      number=8, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=160,
)

DESCRIPTOR.message_types_by_name['TorcsData'] = _TORCSDATA

TorcsData = _reflection.GeneratedProtocolMessageType('TorcsData', (_message.Message,), dict(
  DESCRIPTOR = _TORCSDATA,
  __module__ = 'torcs_data_pb2'
  # @@protoc_insertion_point(class_scope:TorcsData)
  ))
_sym_db.RegisterMessage(TorcsData)


# @@protoc_insertion_point(module_scope)
